version: 2

defaults: &defaults
  working_directory: ~/ledger-live-desktop
  environment:
    BASH_ENV: "~/.bashrc"

jobs:
  build-macos:
    <<: *defaults
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run: bash scripts/ci/macos-setup.sh
      - run: cat ~/.bashrc
      - run: node --version
      - restore_cache:
          keys:
            - v13-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v13-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: bash scripts/ci/macos-ci.sh
      - run: yarn release

  build-linux:
    <<: *defaults
    docker:
      - image: circleci/node:8.11.3-stretch-browsers
    steps:
      - run: sudo apt-get install -y libudev-dev
      - checkout
      - restore_cache:
          keys:
            - v14-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v14-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn flow
      - run: yarn test
      - run: yarn release

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-macos
